# Permalinks
permalink:        pretty

# Setup
url:              https://arjunpoddar.github.io/

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          https://arjunpoddar.github.io/

title:            Arjun Poddar

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  A learning machine.

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /hydejack/public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Arjun Poddar'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        qwtel
  github:         qwtel

  # Setting a disqus username will enable the comment section
  disqus:         qwtel

  # This photo will be used in the about section
  photo:          http://qwtel.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Florian or [`@qwtel`](https://www.twitter.com/qwtel), which isn't an acronym,
    I just [wanted a short username](http://qwtel.com/how-to-find-a-short-username) and that one happened to be available.

    Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
